#22350 - Ajusta validacoes do container e imagem nos arquivos Jenkinsfile

diff --git a/jenkins/JenkinsfileCrt b/jenkins/JenkinsfileCrt
--- a/jenkins/JenkinsfileCrt
+++ b/jenkins/JenkinsfileCrt
@@ -11,12 +11,13 @@ pipeline {
         ACTUATOR_PORT = "8081"
         PROFILE = "certificacao"
         DOCKER_CRT = "docker --context crt"
+        DOCKER_LOCAL = "docker --context default"
         CONTAINER_NAME = "autenticacao-api-crt"
         BRANCH_NAME = "${GIT_BRANCH.split("/")[1]}"
         APPLICATION_TAG = "${BRANCH_NAME}-${BUILD_NUMBER}"
         HARBOR_LOGIN = "https://harbor.xbrain.com.br/ -u ${HARBOR_USER} -p ${HARBOR_PASSWORD}"
         HARBOR_URL = "harbor.xbrain.com.br/conexao-claro-brasil/${CONTAINER_NAME}:${APPLICATION_TAG}"
-        CURRENT_IMAGE = sh(script: "${DOCKER_CRT} ps -a -f name=^${CONTAINER_NAME}\$ --format '{{.Image}}'", returnStdout: true).trim()
+        CURRENT_IMAGE = sh(script: "${DOCKER_CRT} images --format '{{.Repository}}:{{.Tag}}' | grep -E /${CONTAINER_NAME}: || echo ''", returnStdout: true).trim()
         JAVA_OPTS = "-Xms1g -Xmx3g -Dspring.profiles.active=${PROFILE} \
                                    -XX:+UseContainerSupport \
                                    -Dcom.sun.management.jmxremote.rmi.port=9092 \
@@ -91,7 +92,19 @@ pipeline {
                                     error "status container ${output}!"
                                 }
                             } else {
-                                sh ''' ${DOCKER_CRT} image rm ${CURRENT_IMAGE} '''
+                                sh '''
+                                    if [ -n "$CURRENT_IMAGE" ]; then
+                                       ${DOCKER_CRT} image rm ${CURRENT_IMAGE}
+                                    fi
+                                    ${DOCKER_LOCAL} image rm ${HARBOR_URL}
+                                    ${DOCKER_LOCAL} rmi ${CONTAINER_NAME}:${APPLICATION_TAG}
+                                    if ${DOCKER_LOCAL} images | awk '{print $1":"$2}' | grep -Eq "^${CURRENT_IMAGE}$"; then
+                                       ${DOCKER_LOCAL} image rm ${CURRENT_IMAGE}
+                                    fi
+                                    if ${DOCKER_LOCAL} images | awk '{print $1":"$2}' | grep -Eq ^$(echo "${CURRENT_IMAGE}" | awk -F'/' '{print $NF}')$; then
+                                       ${DOCKER_LOCAL} rmi $(echo ${CURRENT_IMAGE} | awk -F'/' '{print $NF}')
+                                    fi
+                                '''
                             }
                         }
                     } catch (error) {
@@ -108,24 +121,42 @@ pipeline {
             }
             steps('Realizando rollback') {
                 sh '''
-                    ${DOCKER_CRT} image rm ${HARBOR_URL}
                     if ${DOCKER_CRT} ps -a --format '{{.Names}}' | grep -Eq "^${CONTAINER_NAME}$"; then
                        ${DOCKER_CRT} stop ${CONTAINER_NAME}
                        ${DOCKER_CRT} rm ${CONTAINER_NAME}
                     fi
-                    ${DOCKER_CRT} run \
-                       --name=${CONTAINER_NAME} \
-                       --restart=unless-stopped \
-                       -p ${PORT} \
-                       -d \
-                       -e JAVA_OPTS="${JAVA_OPTS}" \
-                       -e ACTUATOR_PORT=${ACTUATOR_PORT} \
-                       -e MINIO_TOKEN=${MINIO_TOKEN} \
-                       -e MINIO_SECRET=${MINIO_SECRET} \
-                       --net network_xbrain \
-                       --memory ${MAX_MEMORY} \
-                       --memory-swap=${MAX_MEMORY} \
-                       ${CURRENT_IMAGE}
+                    if ${DOCKER_CRT} images | awk '{print $1":"$2}' | grep -Eq "^${HARBOR_URL}$"; then
+                       ${DOCKER_CRT} image rm ${HARBOR_URL}
+                    fi
+                    ${DOCKER_LOCAL} image rm ${HARBOR_URL}
+                    ${DOCKER_LOCAL} rmi ${CONTAINER_NAME}:${APPLICATION_TAG}
+                    if ${DOCKER_LOCAL} images | grep -Eq $(echo "^${CONTAINER_NAME}$" | awk -F'/' '{print $NF}'); then
+                       ${DOCKER_LOCAL} rmi $(echo ${HARBOR_URL} | awk -F'/' '{print $NF}')
+                    fi
+                    if ${DOCKER_LOCAL} images | awk '{print $1":"$2}' | grep -Eq "^${CURRENT_IMAGE}$"; then
+                       ${DOCKER_LOCAL} image rm ${CURRENT_IMAGE}
+                    fi
+                    if ${DOCKER_LOCAL} images | awk '{print $1":"$2}' | grep -Eq ^$(echo "${CURRENT_IMAGE}" | awk -F'/' '{print $NF}')$; then
+                       ${DOCKER_LOCAL} rmi $(echo ${CURRENT_IMAGE} | awk -F'/' '{print $NF}')
+                    fi
+
+                    if [ -n "$CURRENT_IMAGE" ]; then
+                       ${DOCKER_CRT} run \
+                          --name=${CONTAINER_NAME} \
+                          --restart=unless-stopped \
+                          -p ${PORT} \
+                          -d \
+                          -e JAVA_OPTS="${JAVA_OPTS}" \
+                          -e ACTUATOR_PORT=${ACTUATOR_PORT} \
+                          -e MINIO_TOKEN=${MINIO_TOKEN} \
+                          -e MINIO_SECRET=${MINIO_SECRET} \
+                          --net network_xbrain \
+                          --memory ${MAX_MEMORY} \
+                          --memory-swap=${MAX_MEMORY} \
+                          ${CURRENT_IMAGE}
+                    else
+                       echo "Current image not found: ${CURRENT_IMAGE}"
+                    fi
                 '''
             }
         }
